# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5268c28d4bf5ea4fde17d29e52030202"
name = "deep-searching"
application_url = "https://posters-processors-oak-brian.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brand-category.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://posters-processors-oak-brian.trycloudflare.com/auth/callback",
  "https://posters-processors-oak-brian.trycloudflare.com/auth/shopify/callback",
  "https://posters-processors-oak-brian.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
