# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "df7d2ca0991305e2c3c59dc1564d172d"
name = "deep-search"
application_url = "https://displays-painful-above-skill.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "reza-test3.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://displays-painful-above-skill.trycloudflare.com/auth/callback",
  "https://displays-painful-above-skill.trycloudflare.com/auth/shopify/callback",
  "https://displays-painful-above-skill.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
