# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fd20007acc2ca52a6081ff38d65c8315"
name = "deep-searching-v7"
application_url = "https://tomatoes-plenty-lancaster-lawn.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brand-category.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://tomatoes-plenty-lancaster-lawn.trycloudflare.com/auth/callback",
  "https://tomatoes-plenty-lancaster-lawn.trycloudflare.com/auth/shopify/callback",
  "https://tomatoes-plenty-lancaster-lawn.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
