# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2a33e441e99905d56c146a489ac46672"
name = "deep-searching-app"
application_url = "https://conclusions-font-casting-level.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brand-category.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://conclusions-font-casting-level.trycloudflare.com/auth/callback",
  "https://conclusions-font-casting-level.trycloudflare.com/auth/shopify/callback",
  "https://conclusions-font-casting-level.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
