# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "90096581f663ca0147f71c47a89db435"
name = "deep-searching-v5"
application_url = "https://sponsors-circus-spectacular-za.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "brand-category.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://sponsors-circus-spectacular-za.trycloudflare.com/auth/callback",
  "https://sponsors-circus-spectacular-za.trycloudflare.com/auth/shopify/callback",
  "https://sponsors-circus-spectacular-za.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
